name: GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build and deploy
        run: |
          npm install
          npm run build  # Ajusta esto según cómo construyas tu proyecto
          mv build/* .
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
